[package]
name = "mayara-server"
version = "0.2.0"
edition = "2021"
rust-version = "1.80.1"

[[bin]]
name = "mayara-server"
path = "src/main.rs"

[features]
navico = []
furuno = []
garmin = []
raymarine = []
# default = ["navico", "furuno", "raymarine"]
default = ["navico", "furuno", "raymarine"]

[dependencies]
mayara-lib = { path = "../mayara-lib" }
anyhow = "1.0.86"
async-trait = "0.1.81"
atomic_float = "1.1.0"
axum = { version = "0.8.1", features = ["http2", "json", "macros", "tokio", "tower-log", "tracing", "ws"] }
axum-core = "0.5.2"
axum-embed = "0.1.0"
base64 = "0.22.1"
bincode = "1.3.3"
bitflags = "2.9.0"
chrono = { version = "0.4.38", features = ["serde"] }
clap = { version = "4.5.15", features = ["derive"] }
clap-verbosity-flag = "2.2.1"
crossbeam = "0.8.4"
directories = "5.0.1"
enum-primitive-derive = "0.3.0"
env_logger = "0.11.5"
futures = "0.3.31"
futures-util = "0.3.31"
headers = "0.4.0"
http = "1.3.1"
http-body-util = "0.1.3"
hyper = "1.5.2"
hyper-util = "0.1.10"
libc = "0.2.156"
log = "0.4.22"
mdns-sd = "0.11.4"
miette = { version = "7.2.0", features = ["fancy"] }
nalgebra = { version = "0.33.2", features = ["std", "macros", "convert-mint", "rand"] }
ndarray = "0.16.1"
network-interface = "2.0.0"
nix = { version = "0.29.0", features = ["net", "socket"] }
nmea-parser = { git = "https://github.com/keesverruijt/nmea-parser", "branch" = "position_precision" }
num-derive = "0.4.2"
num-traits = "0.2.19"
once_cell = "1.21.1"
protobuf = "3.5.1"
rust-embed = { version = "8.5.0", features = ["axum","interpolate-folder-path"] }
serde = { version = "1.0.206", features = ["derive", "serde_derive"] }
serde_json = "1.0.125"
serde_repr = "0.1.19"
serde_with = { version = "3.9.0", features = ["macros"] }
sha1 = "0.10.6"
socket2 = "0.5.7"
strum = { version = "0.27.1", features = ["derive"] }
terminal_size = "0.3.0"
thiserror = "1.0.63"
time = { version = "0.3.36", features = ["formatting"] }
tokio = { version = "1", features = ["full"] }
tokio-graceful-shutdown = "0.15.1"
tokio-shutdown = "0.1.4"
# tokio-tungstenite = "0.26.2"
tokio-tungstenite = { git = "https://github.com/keesverruijt/tokio-tungstenite", features = [ "deflate" ] }
tokio-util = "0.7.13"
tower = "0.5.2"
tungstenite = { git = "https://github.com/keesverruijt/tungstenite-rs.git", branch = "permessage-deflate", features = [ "deflate" ] }
# tungstenite = { path = "../tungstenite-rs", features = [ "handshake", "deflate" ] }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.4"
system-configuration = "0.6.1"

[target.'cfg(target_os = "linux")'.dependencies]
netlink-sys = { version = "0.8.4", features = ["tokio", "tokio_socket"] }
rtnetlink = "0.14.1"

[target.'cfg(target_os = "windows")'.dependencies]
w32-error = "1.0.0"
windows = { version = "0.59.0", features = ["Win32_NetworkManagement_IpHelper", "Win32_NetworkManagement_WiFi", "Win32_Networking_WinSock", "Win32_System", "Win32_System_Threading", "Win32_Security", "Win32_System_Diagnostics", "Win32_System_Diagnostics_Debug", "Win32_System_IO", "Win32_NetworkManagement_Ndis", "Win32_Networking_WinSock", "Win32_System_SystemServices" ] }

[build-dependencies]
protobuf-codegen = "3.5.1"
openssl = { version = "0.10", features = ["vendored"] }
reqwest = { version = "0.12.7", default-features = false, features = ["rustls-tls", "blocking"] }
rust-embed = { version = "8.5.0", features = ["axum","interpolate-folder-path"] }
